services:
  - type: web
    name: zero-harm-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    branch: main
    repo: https://github.com/Zero-Harm-AI-LLC/zero-harm-ai-backend

